### PR TITLE
Omnipay 3+ compatibility

### PR DESCRIPTION
**Pull request by iki-cz**
Omnipay 3+ composer.json definition changes, testing site URL correction.

### CODE REVIEW

**Comment by tomaj** [comment]
Thank you for this pull request. I have few things about it:
 - can you rebase/merge actual version from master? i've fixed few things
 - i've also tried actual version with platby.tomaj.sk and it is working correctly with signing. Can you describe more deeply this:
``` //return 'https://platby.tomaj.sk/payment/eplatby-hmac'; //wrong sign calculation``` what is the problem?

Thanks

**Comment by iki-cz** [comment]
Ok, I will rebase the code. 

I've created example POST requests to your testing site and VUB site. Your site returns "Wrong sign", but the VUB test site returns "OK". https://jsfiddle.net/ikicz/q7ymwhzr/

**Comment by tomaj** [comment]
Thank you merging master to your branch.

About problem with signing in platby.tomaj.sk - there should be another problem. VUB test payment server is using different shared key `36fmtvHtjyRAieZ9k+x9zldZIYhSx/vh22iaBG9n1aOd1ncFKrUCeR7gAE5Dg2D1` in test.php there are `1111111111111111111111111111111111111111111111111111111111111111` and it works with platby.tomaj.sk - https://www.dropbox.com/s/p6yd0k8s7euqs3y/Screenshot%202019-02-25%2019.52.14.png?dl=0
(I've tried to put all your payment data to test.php and it is working)

So there is no need change this test payment url and it could stay platby.tomaj.sk if there are actual shared secret.

**Comment by iki-cz** [comment]
You are right! My bad. I didn't noticed changed password (I had the password from VUB docs). So platby.tomaj.sk is ok. I'ts just VUB test URL change.

**Pull request merged**
